FROM openjdk:8-jdk-alpine
EXPOSE 8093
COPY target/softib-transactionManager-0.0.1-SNAPSHOT.war softib-transactionManager-0.0.1-SNAPSHOT.war
ENTRYPOINT ["java","-jar","/softib-transactionManager-0.0.1-SNAPSHOT.war"]